### ISSUE TITLE
Update RestSharp refactored namespaces

### ISSUE THREAD

**Issue by djelekar** [Salience/FluentApi#1]
## Expected Behavior
Method **FluentClient.SetAuthenticator(RestSharp.Authenticators.IAuthenticator)** references IAuthenticator argument from new assembly (RestSharp 106.2.1)

## Actual Behavior
Method **FluentClient.SetAuthenticator(RestSharp.IAuthenticator)** references IAuthenticator argument from old assembly (RestSharp 105.0.1)

## Steps to Reproduce the Problem

  1. Have installed RestSharp 105.0.1 and Salience.FluentApi 1.6.0. Reference IAuthenticator in code.
  2. Update to RestSharp 106.2.1
  3. Observe the issue

## Specifications

  - Version: 1.6.0
  - Platform: Windows
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by djelekar** [comment]
I would be great if we can provide support for RestSharp 106.2.1. 👍

**Comment by jpatte** [comment]
Closing as this was solved by properly updating to more recent versions of RestSharp.
